export const arrHeaderMainLinks: { name: string; path: string }[] = [
  { name: "Brands", path: "" },
  { name: "Deals", path: "" },
  { name: "New", path: "" },
  { name: "Men", path: "" },
  { name: "Women", path: "" },
  { name: "Kids", path: "" },
  { name: "Sneakers", path: "" },
  { name: "Shoes", path: "" },
  { name: "Apparel", path: "" },
  { name: "Accessories", path: "" },
  { name: "More Categories", path: "" },
];
export const brands = [
  { name: "All Brands", path: "" },
  { name: "A", path: "" },
  { name: "B", path: "" },
  { name: "C", path: "" },
  { name: "D", path: "" },
  { name: "E", path: "" },
  { name: "F", path: "" },
  { name: "G", path: "" },
  { name: "H", path: "" },
  { name: "I", path: "" },
  { name: "J", path: "" },
  { name: "K", path: "" },
  { name: "L", path: "" },
  { name: "M", path: "" },
  { name: "N", path: "" },
  { name: "O", path: "" },
  { name: "P", path: "" },
  { name: "Q", path: "" },
  { name: "R", path: "" },
  { name: "S", path: "" },
  { name: "T", path: "" },
  { name: "U", path: "" },
  { name: "V", path: "" },
  { name: "W", path: "" },
  { name: "X", path: "" },
  { name: "Y", path: "" },
  { name: "Z", path: "" },
  { name: "#", path: "" },
  { name: "Top Brands", path: "" },
  { name: "Nike", path: "" },
  { name: "adidas", path: "" },
  { name: "Fear of God", path: "" },
  { name: "UGG", path: "" },
  { name: "Crocs", path: "" },
  { name: "Puma", path: "" },
  { name: "Converse", path: "" },
  { name: "Jordan", path: "" },
  { name: "New Balance", path: "" },
  { name: "Supreme", path: "" },
  { name: "ASICS", path: "" },
  { name: "BAPE", path: "" },
  { name: "Yeezy", path: "" },
  { name: "Sony", path: "" },
  { name: "Trending Brands", path: "" },
  { name: "Louis Vuitton", path: "" },
  { name: "Balenciaga", path: "" },
  { name: "Denim Tears", path: "" },
  { name: "Sp5der", path: "" },
  { name: "Vans", path: "" },
  { name: "Pop Mart", path: "" },
  { name: "Kith", path: "" },
  { name: "Travis Scott", path: "" },
  { name: "Gucci", path: "" },
  { name: "OFF-WHITE", path: "" },
  { name: "Timberland", path: "" },
  { name: "Palace", path: "" },
  { name: "Hellstar", path: "" },
  { name: "Chrome Hearts", path: "" },
];
export const deals = [
  { name: "Below Retail", path: "" },
  { name: "adidas", path: "" },
  { name: "Air Jordan", path: "" },
  { name: "ASICS", path: "" },
  { name: "Converse", path: "" },
  { name: "New Balance", path: "" },
  { name: "Nike", path: "" },
  { name: "Yeezy", path: "" },
  { name: "Trending Deals", path: "" },
  { name: "Sneakers", path: "" },
  { name: "Shoes", path: "" },
  { name: "Apparel", path: "" },
  { name: "Accessories", path: "" },
  { name: "Collectibles", path: "" },
  { name: "Electronics", path: "" },
  { name: "Trading Cards", path: "" },
  { name: "Luxury Below Retail", path: "" },
  { name: "Burberry", path: "" },
  { name: "CDG Play", path: "" },
  { name: "Gucci Accessories", path: "" },
  { name: "Jacquemus", path: "" },
  { name: "Luxury Sneakers", path: "" },
  { name: "OFF-WHITE", path: "" },
  { name: "Palm Angels", path: "" },
  { name: "More Below Retail", path: "" },
  { name: "Bearbrick", path: "" },
  { name: "Fear Of God", path: "" },
  { name: "LEGO", path: "" },
  { name: "Sunglasses", path: "" },
  { name: "Supreme", path: "" },
  { name: "UGG", path: "" },
  { name: "Staff Pick Steals", path: "" },
  { name: "Air Jordan 1 Green Glow", path: "" },
  { name: "Burberry Letter Graphic Cotton Blend Zip Hoodie", path: "" },
  { name: "Converse x CDG All Star Hi", path: "" },
  { name: "Nike Dunk Pacific Moss", path: "" },
  { name: "Prada Symbole Sunglasses", path: "" },
  {
    name: "The North Face 1996 Retro Nuptse 700 Fill Packable Jacket",
    path: "",
  },
];
export const newarray: { name: string; path: string }[] = [
  { name: "Trending Brands", path: "" },
  { name: "ASICS", path: "" },
  { name: "UGG", path: "" },
  { name: "Denim Tears", path: "" },
  { name: "Hellstar", path: "" },
  { name: "Mihara Yasuhiro", path: "" },
  { name: "Onitsuka Tiger", path: "" },
  { name: "Stanley", path: "" },
  { name: "Featured New Products", path: "" },
  { name: "Nike SB Dunk Low Verdy Visty", path: "" },
  { name: "AJ4 A Ma Maniére Fossil Stone", path: "" },
  { name: "Travis Scott AJ1 Low Medium Olive", path: "" },
  { name: "Nike Swoosh Pillow", path: "" },
  { name: "Playstation Portal", path: "" },
  { name: "Supreme x Margiela", path: "" },
  { name: "Swatch x Omega Snoopy", path: "" },
  { name: "Releases", path: "" },
  { name: "Upcoming Sneakers", path: "" },
  { name: "Recent Sneakers", path: "" },
  { name: "Recent Apparel", path: "" },
  { name: "Recent Accessories", path: "" },
  { name: "Recent Collectibles", path: "" },
  { name: "View All Upcoming", path: "" },
  { name: "Xpress Ship Available", path: "" },
  { name: "adidas", path: "" },
  { name: "Air Jordan", path: "" },
  { name: "Crocs", path: "" },
  { name: "New Balance", path: "" },
  { name: "Nike", path: "" },
  { name: "UGG", path: "" },
  { name: "Yeezy", path: "" },
  { name: "News & Highlights", path: "" },
  { name: "This is Love Campaign", path: "" },
  { name: "Shareable Lists", path: "" },
  { name: "Xpress Shipping", path: "" },
  { name: "Big Facts Report", path: "" },
  { name: "Picks For Her", path: "" },
  { name: "Tell your friends - Give $10, get $10", path: "" },
];
