export const brandsData = [
  {
    path: "",
    title: "All Brands",
    sub_link: [
      { name: "A", path: "" },
      { name: "B", path: "" },
      { name: "C", path: "" },
      { name: "D", path: "" },
      { name: "E", path: "" },
      { name: "F", path: "" },
      { name: "G", path: "" },
      { name: "H", path: "" },
      { name: "I", path: "" },
      { name: "J", path: "" },
      { name: "K", path: "" },
      { name: "L", path: "" },
      { name: "M", path: "" },
      { name: "N", path: "" },
      { name: "O", path: "" },
      { name: "P", path: "" },
      { name: "Q", path: "" },
      { name: "R", path: "" },
      { name: "S", path: "" },
      { name: "T", path: "" },
      { name: "U", path: "" },
      { name: "V", path: "" },
      { name: "W", path: "" },
      { name: "X", path: "" },
      { name: "Y", path: "" },
      { name: "Z", path: "" },
      { name: "#", path: "" },
    ],
  },
  {
    path: "",
    title: "Top Brands",
    sub_link: [
      { name: "Nike", path: "" },
      { name: "adidas", path: "" },
      { name: "Fear of God", path: "" },
      { name: "UGG", path: "" },
      { name: "Crocs", path: "" },
      { name: "Puma", path: "" },
      { name: "Converse", path: "" },
      { name: "Jordan", path: "" },
      { name: "New Balance", path: "" },
      { name: "Supreme", path: "" },
      { name: "ASICS", path: "" },
      { name: "BAPE", path: "" },
      { name: "Yeezy", path: "" },
      { name: "Sony", path: "" },
    ],
  },
  {
    path: "",
    title: "Trending Brands",
    sub_link: [
      { name: "Louis Vuitton", path: "" },
      { name: "Gucci", path: "" },
      { name: "Balenciaga", path: "" },
      { name: "OFF-WHITE", path: "" },
      { name: "Vans", path: "" },
      { name: "Pop Mart", path: "" },
      { name: "Kith", path: "" },
      { name: "Travis Scott", path: "" },
      { name: "Denim Tears", path: "" },
      { name: "Sp5der", path: "" },
      { name: "Timberland", path: "" },
      { name: "Palace", path: "" },
      { name: "Hellstar", path: "" },
      { name: "Stanley", path: "" },
    ],
  },
];
export const dealsData = [
  {
    path: "",
    title: "Below Retail",
    sub_link: [
      { name: "adidas", path: "" },
      { name: "Air Jordan", path: "" },
      { name: "ASICS", path: "" },
      { name: "Converse", path: "" },
      { name: "New Balance", path: "" },
      { name: "Nike", path: "" },
      { name: "Yeezy", path: "" },
    ],
  },
  {
    path: "",
    title: "Trending Deals",
    sub_link: [
      { name: "Sneakers", path: "" },
      { name: "Shoes", path: "" },
      { name: "Apparel", path: "" },
      { name: "Accessories", path: "" },
      { name: "Collectibles", path: "" },
      { name: "Electronics", path: "" },
      { name: "Trading Cards", path: "" },
    ],
  },
  {
    path: "",
    title: "Luxury Below Retail",
    sub_link: [
      { name: "Burberry", path: "" },
      { name: "CDG Play", path: "" },
      { name: "Gucci Accessories", path: "" },
      { name: "Jacquemus", path: "" },
      { name: "Luxury Sneakers", path: "" },
      { name: "OFF-WHITE", path: "" },
      { name: "Palm Angels", path: "" },
    ],
  },
  {
    path: "",
    title: "More Below Retail",
    sub_link: [
      { name: "Bearbrick", path: "" },
      { name: "Fear Of God", path: "" },
      { name: "LEGO", path: "" },
      { name: "Sunglasses", path: "" },
      { name: "Supreme", path: "" },
      { name: "UGG", path: "" },
    ],
  },
  {
    path: "",
    title: "More Below Retail",
    sub_link: [
      { name: "Bearbrick", path: "" },
      { name: "Fear Of God", path: "" },
      { name: "LEGO", path: "" },
      { name: "Sunglasses", path: "" },
      { name: "Supreme", path: "" },
      { name: "UGG", path: "" },
    ],
  },
];

export const arrHeaderMainLinks: {
  name: string;
  path: string;
  content?: any;
}[] = [
  { name: "Brands", path: "", content: brandsData },
  { name: "Deals", path: "", content: dealsData },
  { name: "New", path: "", content: dealsData },
  { name: "Men", path: "", content: dealsData },
  { name: "Women", path: "", content: dealsData },
  { name: "Kids", path: "", content: dealsData },
  { name: "Sneakers", path: "", content: dealsData },
  { name: "Shoes", path: "", content: dealsData },
  { name: "Apparel", path: "", content: dealsData },
  { name: "Accessories", path: "", content: dealsData },
  { name: "More Categories", path: "", content: dealsData },
];
